config/routes.rb
Rails.application.routes.draw do

  get 'open_order_report', to: 'open_order_report#index'
  post 'open_order_report', to: 'open_order_report#index'
  get 'repair_order_report', to: 'repair_order_report#index'
  post 'repair_order_report', to: 'repair_order_report#index'
  get 'warranty_report', to: 'warranty_report#index'
  post 'warranty_report', to: 'warranty_report#index'
  get 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  post 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'top_customer_report', to: 'top_customer_report#index'
  post 'top_customer_report', to: 'top_customer_report#index'
  get 'not_started_order_report', to: 'not_started_order_report#index'
  get 'on_hold_order_report', to: 'on_hold_order_report#index'
  get 'awaiting_parts_report', to: 'awaiting_parts_report#index'
  get 'completed_order_report', to:'completed_order_report#index'









  resources :device_colors
  root 'dashboard#index', as: 'dashboard_index'
  resources :device_post_tests
  resources :device_pre_tests
  resources :tests
  resources :repair_order_items
  resources :devices
  resources :repair_orders
  resources :customers
  resources :repair_order_statuses
  resources :technicians
  resources :device_components
  resources :device_versions
  resources :technician_statuses
  resources :device_component_statuses
  resources :device_manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/repair_order_statuses_controller.rb
class RepairOrderStatusesController < ApplicationController
  before_action :set_repair_order_status, only: [:show, :edit, :update, :destroy]

  # GET /repair_order_statuses
  # GET /repair_order_statuses.json
  def index
    @repair_order_statuses = RepairOrderStatus.all
  end

  # GET /repair_order_statuses/1
  # GET /repair_order_statuses/1.json
  def show
  end

  # GET /repair_order_statuses/new
  def new
    @repair_order_status = RepairOrderStatus.new
  end

  # GET /repair_order_statuses/1/edit
  def edit
  end

  # POST /repair_order_statuses
  # POST /repair_order_statuses.json
  def create
    @repair_order_status = RepairOrderStatus.new(repair_order_status_params)

    respond_to do |format|
      if @repair_order_status.save
        format.html { redirect_to @repair_order_status, notice: 'Repair order status was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order_status }
      else
        format.html { render :new }
        format.json { render json: @repair_order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_order_statuses/1
  # PATCH/PUT /repair_order_statuses/1.json
  def update
    respond_to do |format|
      if @repair_order_status.update(repair_order_status_params)
        format.html { redirect_to @repair_order_status, notice: 'Repair order status was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order_status }
      else
        format.html { render :edit }
        format.json { render json: @repair_order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_order_statuses/1
  # DELETE /repair_order_statuses/1.json
  def destroy
    @repair_order_status.destroy
    respond_to do |format|
      format.html { redirect_to repair_order_statuses_url, notice: 'Repair order status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_order_status
      @repair_order_status = RepairOrderStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_order_status_params
      params.require(:repair_order_status).permit(:repair_order_status)
    end
end

app/helpers/repair_order_statuses_helper.rb
module RepairOrderStatusesHelper
end

app/views/repair_order_statuses/_form.html.erb
<%= form_with(model: repair_order_status, local: true) do |form| %>
  <% if repair_order_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair_order_status.errors.count, "error") %> prohibited this repair_order_status from being saved:</h2>

      <ul>
      <% repair_order_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :repair_order_status, "Status Type" %>
    <%= form.text_field :repair_order_status, id: :repair_order_status_repair_order_status %>
  </div>

    <div class="actions">
      <button type="submit" class="btn btn-outline btl-lg"> Create Repair Order Status</button>
    </div>


<% end %>

app/views/repair_order_statuses/edit.html.erb
<h1>Editing Repair Order Status</h1>

<%= render 'form', repair_order_status: @repair_order_status %>

<%= link_to 'Show', @repair_order_status %> |
<%= link_to 'Back', repair_order_statuses_path %>

app/views/repair_order_statuses/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Statuses for the Repair Orders</h1>
  <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Status Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_order_statuses.each do |repair_order_status| %>
      <tr>
        <td><%= repair_order_status.repair_order_status %></td>
        <td><%= link_to 'View', edit_repair_order_status_path(repair_order_status) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1">
    <a class="btn btn-outline" href="repair_order_statuses/new">New Repair Order Status</a>
  </div>
</div>

app/views/repair_order_statuses/new.html.erb
<div class="container">
<h1>Create A New Repair Order Status</h1>

<%= render 'form', repair_order_status: @repair_order_status %>

<%= link_to 'Back', repair_order_statuses_path %>
</div>

app/views/repair_order_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repair Order Status:</strong>
  <%= @repair_order_status.repair_order_status %>
</p>

<%= link_to 'Edit', edit_repair_order_status_path(@repair_order_status) %> |
<%= link_to 'Back', repair_order_statuses_path %>