config/routes.rb
Rails.application.routes.draw do

  get 'open_order_report', to: 'open_order_report#index'
  post 'open_order_report', to: 'open_order_report#index'
  get 'repair_order_report', to: 'repair_order_report#index'
  post 'repair_order_report', to: 'repair_order_report#index'
  get 'warranty_report', to: 'warranty_report#index'
  post 'warranty_report', to: 'warranty_report#index'
  get 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  post 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'top_customer_report', to: 'top_customer_report#index'
  post 'top_customer_report', to: 'top_customer_report#index'
  get 'not_started_order_report', to: 'not_started_order_report#index'
  get 'on_hold_order_report', to: 'on_hold_order_report#index'
  get 'awaiting_parts_report', to: 'awaiting_parts_report#index'
  get 'completed_order_report', to:'completed_order_report#index'









  resources :device_colors
  root 'dashboard#index', as: 'dashboard_index'
  resources :device_post_tests
  resources :device_pre_tests
  resources :tests
  resources :repair_order_items
  resources :devices
  resources :repair_orders
  resources :customers
  resources :repair_order_statuses
  resources :technicians
  resources :device_components
  resources :device_versions
  resources :technician_statuses
  resources :device_component_statuses
  resources :device_manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device_version.rb
class DeviceVersion < ApplicationRecord
  belongs_to :device_manufacturer
  has_many :devices
  has_many :device_components

  validates :device_version_name, presence: true
end

app/controllers/device_versions_controller.rb
class DeviceVersionsController < ApplicationController
  before_action :set_device_version, only: [:show, :edit, :update, :destroy]

  # GET /device_versions
  # GET /device_versions.json
  def index
    @device_versions = DeviceVersion.all
  end

  # GET /device_versions/1
  # GET /device_versions/1.json
  def show
  end

  # GET /device_versions/new
  def new
    @device_version = DeviceVersion.new
  end

  # GET /device_versions/1/edit
  def edit
  end

  # POST /device_versions
  # POST /device_versions.json
  def create
    @device_version = DeviceVersion.new(device_version_params)

    respond_to do |format|
      if @device_version.save
        format.html { redirect_to @device_version, notice: 'Device version was successfully created.' }
        format.json { render :show, status: :created, location: @device_version }
      else
        format.html { render :new }
        format.json { render json: @device_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_versions/1
  # PATCH/PUT /device_versions/1.json
  def update
    respond_to do |format|
      if @device_version.update(device_version_params)
        format.html { redirect_to @device_version, notice: 'Device version was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_version }
      else
        format.html { render :edit }
        format.json { render json: @device_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_versions/1
  # DELETE /device_versions/1.json
  def destroy
    @device_version.destroy
    respond_to do |format|
      format.html { redirect_to device_versions_url, notice: 'Device version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_version
      @device_version = DeviceVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_version_params
      params.require(:device_version).permit(:device_version_name, :device_manufacturer_id)
    end
end

app/helpers/device_versions_helper.rb
module DeviceVersionsHelper
end

app/views/device_versions/_form.html.erb
<%= form_with(model: device_version, local: true) do |form| %>
  <% if device_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device_version.errors.count, "error") %> prohibited this device_version from being saved:</h2>

      <ul>
      <% device_version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_version_name, "Version" %>
    <%= form.text_field :device_version_name, id: :device_version_device_version_name %>
  </div>


  <div class="field">
    <%= form.label :device_manufacturer_id, "Manufacturer" %>
    <%= form.collection_select :device_manufacturer_id, DeviceManufacturer.all, :id, :device_manu_name %>
  </div>


    <div class="actions">
      <button type="submit" class="btn btn-outline btl-lg"> Create Device Version</button>
    </div>

<% end %>

app/views/device_versions/edit.html.erb
<h1>Editing Device Version</h1>

<%= render 'form', device_version: @device_version %>

<%= link_to 'Show', @device_version %> |
<%= link_to 'Back', device_versions_path %>

app/views/device_versions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Versions</h1>
  <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_versions.each do |device_version| %>
      <tr>
        <td><%= device_version.device_version_name %></td>
        <td><%= device_version.device_manufacturer.device_manu_name %></td>
        <td><%= link_to 'View', edit_device_version_path(device_version) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1">
      <a class="btn btn-outline" href="device_versions/new">New Device Version</a>
    </div>


</div>

app/views/device_versions/new.html.erb
<div class="container">
<h1>Create A New Device Version</h1>

<%= render 'form', device_version: @device_version %>

<%= link_to 'Back', device_versions_path %>
</div>

app/views/device_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version Name:</strong>
  <%= @device_version.device_version_name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @device_version.device_manufacturer.device_manu_name %>
</p>

<%= link_to 'Edit', edit_device_version_path(@device_version) %> |
<%= link_to 'Back', device_versions_path %>