config/routes.rb
Rails.application.routes.draw do

  get 'open_order_report', to: 'open_order_report#index'
  post 'open_order_report', to: 'open_order_report#index'
  get 'repair_order_report', to: 'repair_order_report#index'
  post 'repair_order_report', to: 'repair_order_report#index'
  get 'warranty_report', to: 'warranty_report#index'
  post 'warranty_report', to: 'warranty_report#index'
  get 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  post 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'top_customer_report', to: 'top_customer_report#index'
  post 'top_customer_report', to: 'top_customer_report#index'
  get 'not_started_order_report', to: 'not_started_order_report#index'
  get 'on_hold_order_report', to: 'on_hold_order_report#index'
  get 'awaiting_parts_report', to: 'awaiting_parts_report#index'
  get 'completed_order_report', to:'completed_order_report#index'









  resources :device_colors
  root 'dashboard#index', as: 'dashboard_index'
  resources :device_post_tests
  resources :device_pre_tests
  resources :tests
  resources :repair_order_items
  resources :devices
  resources :repair_orders
  resources :customers
  resources :repair_order_statuses
  resources :technicians
  resources :device_components
  resources :device_versions
  resources :technician_statuses
  resources :device_component_statuses
  resources :device_manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/repair_order_item.rb
class RepairOrderItem < ApplicationRecord
  belongs_to :device_component
  belongs_to :technician
  belongs_to :device
  belongs_to :repair_order_status


  before_update :update_w_date
  before_update :update_wrepair_date

  def warranty_date
    x = Date.today + 90
    update_columns(warranty_expire_date: x)
  end

  def update_w_date
    self.warranty_expire_date = Date.today + 90 if repair_order_status_id == 6 # maybe better Time.now?
  end

  def update_wrepair_date
    self.warranty_repair_date = Date.today if repaired_as_warranty == true # maybe better Time.now?
  end

end

app/controllers/repair_order_items_controller.rb
class RepairOrderItemsController < ApplicationController
  before_action :set_repair_order_item, only: [:show, :edit, :update, :destroy]

  # GET /repair_order_items
  # GET /repair_order_items.json
  def index
    @repair_order_items = RepairOrderItem.all
  end

  # GET /repair_order_items/1
  # GET /repair_order_items/1.json
  def show
  end

  # GET /repair_order_items/new
  def new
    @repair_order_item = RepairOrderItem.new
  end

  # GET /repair_order_items/1/edit
  def edit
  end

  # POST /repair_order_items
  # POST /repair_order_items.json
  def create
    @repair_order_item = RepairOrderItem.new(repair_order_item_params)

    respond_to do |format|
      if @repair_order_item.save
        format.html { redirect_to @repair_order_item, notice: 'Repair order item was successfully created.' }
        format.json { render :show, status: :created, location: @repair_order_item }
      else
        format.html { render :new }
        format.json { render json: @repair_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_order_items/1
  # PATCH/PUT /repair_order_items/1.json
  def update
    respond_to do |format|
      if @repair_order_item.update(repair_order_item_params)
        format.html { redirect_to @repair_order_item, notice: 'Repair order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_order_item }
      else
        format.html { render :edit }
        format.json { render json: @repair_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_order_items/1
  # DELETE /repair_order_items/1.json
  def destroy
    @repair_order_item.destroy
    respond_to do |format|
      format.html { redirect_to repair_order_items_url, notice: 'Repair order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_order_item
      @repair_order_item = RepairOrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_order_item_params
      params.require(:repair_order_item).permit(:repair_order_status_id, :device_component_id, :technician_id, :warranty_expire_date, :warranty_coverage_notes, :repaired_as_warranty, :warranty_repair_date, :price, :device_id)
    end
end

app/helpers/repair_order_items_helper.rb
module RepairOrderItemsHelper
end

app/views/repair_order_items/_form.html.erb
<%= form_with(model: repair_order_item, local: true) do |form| %>
  <% if repair_order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair_order_item.errors.count, "error") %> prohibited this repair_order_item from being saved:</h2>

      <ul>
      <% repair_order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_component_id, "Component" %>
    <%= form.collection_select :device_component_id, DeviceComponent.all, :id, :device_comp_name %>
  </div>

  <div class="field">
    <%= form.label :technician_id, "Technician" %>
    <%= form.collection_select :technician_id, Technician.all, :id, :tech_name %>
  </div>

  <div class="field">
    <%= form.label :warranty_expire_date, "Warranty Expiration Date" %>
    <%= form.date_select :warranty_expire_date, id: :repair_order_item_warranty_expire_date %>
  </div>

  <div class="field">
    <%= form.label :warranty_coverage_notes, "Warranty Coverage Notes" %>
    <%= form.text_field :warranty_coverage_notes, id: :repair_order_item_warranty_coverage_notes %>
  </div>

  <div class="field">
    <%= form.label :repaired_as_warranty, "Reaired As Warranty" %>
    <%= form.check_box :repaired_as_warranty, id: :repair_order_item_repaired_as_warranty %>
  </div>

  <div class="field">
    <%= form.label :warranty_repair_date, "Warranty Repair Date" %>
    <%= form.date_select :warranty_repair_date, id: :repair_order_item_warranty_repair_date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :repair_order_item_price %>
  </div>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id, id: :repair_order_item_device_id %>
  </div>

    <div class="actions">
      <button type="submit" class="btn btn-outline btl-lg"> Create Repair Order Item</button>
    </div>
<% end %>

app/views/repair_order_items/edit.html.erb
<h1>Editing Repair Order Item</h1>

<%= render 'form', repair_order_item: @repair_order_item %>

<%= link_to 'Show', @repair_order_item %> |
<%= link_to 'Back', repair_order_items_path %>

app/views/repair_order_items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Items in Repair Orders</h1>
  <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Component</th>
      <th>Technician</th>
      <th>Warranty Expiration Date</th>
      <th>Warranty Coverage Notes</th>
      <th>Repaired as Warranty</th>
      <th>Warranty Repair Date</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_order_items.each do |repair_order_item| %>
      <tr>
        <td><%= repair_order_item.device_component_id %></td>
        <td><%= repair_order_item.technician %></td>
        <td><%= repair_order_item.warranty_expire_date %></td>
        <td><%= repair_order_item.warranty_coverage_notes %></td>
        <td><%= repair_order_item.repaired_as_warranty %></td>
        <td><%= repair_order_item.warranty_repair_date %></td>
        <td><%= repair_order_item.device %></td>

        <td><%= link_to 'View', edit_repair_order_item_path(repair_order_item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1">
    <a class="btn btn-outline" href="repair_order_items/new">New Repair Order Item</a>
  </div>
</div>

app/views/repair_order_items/new.html.erb
<div class="container">
<h1>Create A New Repair Order Item</h1>

<%= render 'form', repair_order_item: @repair_order_item %>

<%= link_to 'Back', repair_order_items_path %>
</div>

app/views/repair_order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @repair_order_item.device_component %>
</p>

<p>
  <strong>Technician:</strong>
  <%= @repair_order_item.technician %>
</p>

<p>
  <strong>Warranty Expiration Date:</strong>
  <%= @repair_order_item.warranty_expire_date %>
</p>

<p>
  <strong>Warranty Coverage Notes:</strong>
  <%= @repair_order_item.warranty_coverage_notes %>
</p>

<p>
  <strong>Repaired As Warranty:</strong>
  <%= @repair_order_item.repaired_as_warranty %>
</p>

<p>
  <strong>Warranty Repair Date:</strong>
  <%= @repair_order_item.warranty_repair_date %>
</p>

<p>
  <strong>Device:</strong>
  <%= @repair_order_item.device %>
</p>

<%= link_to 'Edit', edit_repair_order_item_path(@repair_order_item) %> |
<%= link_to 'Back', repair_order_items_path %>