config/routes.rb
Rails.application.routes.draw do

  get 'open_order_report', to: 'open_order_report#index'
  post 'open_order_report', to: 'open_order_report#index'
  get 'repair_order_report', to: 'repair_order_report#index'
  post 'repair_order_report', to: 'repair_order_report#index'
  get 'warranty_report', to: 'warranty_report#index'
  post 'warranty_report', to: 'warranty_report#index'
  get 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  post 'repair_component_per_order_report', to:'repair_component_per_order_report#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'popular_devices', to:'popular_devices#index'
  get 'top_customer_report', to: 'top_customer_report#index'
  post 'top_customer_report', to: 'top_customer_report#index'
  get 'not_started_order_report', to: 'not_started_order_report#index'
  get 'on_hold_order_report', to: 'on_hold_order_report#index'
  get 'awaiting_parts_report', to: 'awaiting_parts_report#index'
  get 'completed_order_report', to:'completed_order_report#index'









  resources :device_colors
  root 'dashboard#index', as: 'dashboard_index'
  resources :device_post_tests
  resources :device_pre_tests
  resources :tests
  resources :repair_order_items
  resources :devices
  resources :repair_orders
  resources :customers
  resources :repair_order_statuses
  resources :technicians
  resources :device_components
  resources :device_versions
  resources :technician_statuses
  resources :device_component_statuses
  resources :device_manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device_component.rb
class DeviceComponent < ApplicationRecord
  belongs_to :device_version
  belongs_to :device_component_status
  has_many :repair_order_items

  validates :device_comp_name, presence: true
  validates :device_comp_color, presence: true
  validates :device_comp_description, presence: true
  validates :device_comp_cost, presence: true

end

app/controllers/device_components_controller.rb
class DeviceComponentsController < ApplicationController
  before_action :set_device_component, only: [:show, :edit, :update, :destroy]

  # GET /device_components
  # GET /device_components.json
  def index
    @device_components = DeviceComponent.all
  end

  # GET /device_components/1
  # GET /device_components/1.json
  def show
  end

  # GET /device_components/new
  def new
    @device_component = DeviceComponent.new
  end

  # GET /device_components/1/edit
  def edit
  end

  # POST /device_components
  # POST /device_components.json
  def create
    @device_component = DeviceComponent.new(device_component_params)

    respond_to do |format|
      if @device_component.save
        format.html { redirect_to @device_component, notice: 'Device component was successfully created.' }
        format.json { render :show, status: :created, location: @device_component }
      else
        format.html { render :new }
        format.json { render json: @device_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_components/1
  # PATCH/PUT /device_components/1.json
  def update
    respond_to do |format|
      if @device_component.update(device_component_params)
        format.html { redirect_to @device_component, notice: 'Device component was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_component }
      else
        format.html { render :edit }
        format.json { render json: @device_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_components/1
  # DELETE /device_components/1.json
  def destroy
    @device_component.destroy
    respond_to do |format|
      format.html { redirect_to device_components_url, notice: 'Device component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_component
      @device_component = DeviceComponent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_component_params
      params.require(:device_component).permit(:device_version_id, :device_comp_name, :device_comp_color, :device_comp_description, :device_component_status_id, :device_comp_cost)
    end
end

app/helpers/device_components_helper.rb
module DeviceComponentsHelper
end

app/views/device_components/_form.html.erb
<%= form_with(model: device_component, local: true) do |form| %>
  <% if device_component.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device_component.errors.count, "error") %> prohibited this device_component from being saved:</h2>

      <ul>
      <% device_component.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_version_id, "Device Version" %>
    <%= form.collection_select :device_version_id, DeviceVersion.all, :id, :device_version_name %>
  </div>

  <div class="field">
    <%= form.label :device_comp_name, "Name" %>
    <%= form.text_field :device_comp_name, id: :device_component_device_comp_name %>
  </div>

  <div class="field">
    <%= form.label :device_comp_color, "Color" %>
    <%= form.text_field :device_comp_color, id: :device_component_device_comp_color %>
  </div>

  <div class="field">
    <%= form.label :device_comp_description, "Description" %>
    <%= form.text_field :device_comp_description, id: :device_component_device_comp_description %>
  </div>

  <div class="field">
    <%= form.label :device_component_status_id, "Status" %>
    <%= form.collection_select :device_component_status_id, DeviceComponentStatus.all, :id, :device_comp_status %>
  </div>

  <div class="field">
    <%= form.label :device_comp_cost, "Cost" %>
    <%= form.text_field :device_comp_cost, id: :device_component_device_comp_cost %>
  </div>

    <div class="actions">
      <button type="submit" class="btn btn-outline btl-lg"> Create Component </button>
    </div>
<% end %>

app/views/device_components/edit.html.erb
<h1>Editing Device Component</h1>

<%= render 'form', device_component: @device_component %>

<%= link_to 'Show', @device_component %> |
<%= link_to 'Back', device_components_path %>

app/views/device_components/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Device Components</h1>
  <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Device Version</th>
      <th>Name</th>
      <th>Color</th>
      <th>Description</th>
      <th>Status</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_components.each do |device_component| %>
      <tr>
        <td><%= device_component.device_version.device_version_name %></td>
        <td><%= device_component.device_comp_name %></td>
        <td><%= device_component.device_comp_color %></td>
        <td><%= device_component.device_comp_description %></td>
        <td><%= device_component.device_component_status.device_comp_status %></td>
        <td><%= number_to_currency(device_component.device_comp_cost) %></td>
        <td><%= link_to 'View', edit_device_component_path(device_component) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

    <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1">
      <a class="btn btn-outline" href="device_components/new">New Component</a>
    </div>
</div>

app/views/device_components/new.html.erb
<div class="container">
<h1>Create A New Device Component</h1>

<%= render 'form', device_component: @device_component %>

<%= link_to 'Back', device_components_path %>
</div>

app/views/device_components/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @device_component.device_version.device_version_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @device_component.device_comp_name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @device_component.device_comp_color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @device_component.device_comp_description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @device_component.device_component_status.device_comp_status %>
</p>

<p>
  <strong>Device comp cost:</strong>
  <%= number_to_currency(@device_component.device_comp_cost) %>
</p>

<%= link_to 'Edit', edit_device_component_path(@device_component) %> |
<%= link_to 'Back', device_components_path %>